[tool.black]
line-length = 99
target-version = ["py38"]
exclude = """
"""

[tool.isort]
profile = "black"
line_length = 99
multi_line_output = 3
lines_after_imports = 2
use_parentheses = true
case_sensitive = true
ensure_newline_before_comments = true
skip_glob = [
    "",
]
