"""create all tables

Revision ID: 6c97a3726611
Revises: 
Create Date: 2021-03-23 01:58:28.874546

"""
from alembic import op
import sqlalchemy as sa

from sweets_store.db.tables.couriers import CouriersTypesEnum


# revision identifiers, used by Alembic.
revision = '6c97a3726611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'car', name='courierstypes'), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('working_hours', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('courier_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('delivery_hours', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('assign_type', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('couriers')
    # ### end Alembic commands ###

    CouriersTypesEnum.drop(op.get_bind(), checkfirst=False)
